### ISSUE TITLE
If IP is not set you have to restart browser

### ISSUE THREAD

**Issue by JPL1** [joshuef/peruse#24] opened 2017-12-20 20:00 UTC
If you try to log in to Alpha 2 having forgotten to set your IP on the invite site, it will not connect even if you set your IP and try again.

To reproduce:
Change IP address
Start Peruse and login - you get `Core error: Unexpected: Could not connect to the SAFE Network`
Set the IP address at invite.maidsafe.net
Hit the login button again - it will log you in
Try any site, e.g. 2048.play - `Setup Incomplete. Connection not available yet.`

You have to close Peruse and restart.
[authenticator.log](https://github.com/joshuef/peruse/files/1576851/authenticator.log)
![cmd-forgot-ip](https://user-images.githubusercontent.com/12783198/34226042-61ed8c12-e5c0-11e7-9663-49a635358704.png)

![cmd-forgot-ip-2](https://user-images.githubusercontent.com/12783198/34229134-193468c8-e5cb-11e7-98f4-c00133445e00.png)

**Comment by JPL1** [comment] 2017-12-20 21:49
Just realised I was using v0.1. The issue still orccurs in 0.3.1 though, but with a different error.
`Core error: Routing interface error -> EventSenderError(EventSubset("SendError(..)"))`

![cmd-forgot-ip-3](https://user-images.githubusercontent.com/12783198/34230237-576994b6-e5cf-11e7-994a-9048480d4929.png)
[authenticator.log](https://github.com/joshuef/peruse/files/1577111/authenticator.log)
[Peruse_Browser.Maidsafe_Ltd.log](https://github.com/joshuef/peruse/files/1577112/Peruse_Browser.Maidsafe_Ltd.log)

**Comment by joshuef** [comment] 2017-12-21 15:31
Thanks @JPL1 for the report. 👍 

Closing this as it's a duplicate of #11 (I've updated the title there to make it clearer).

**Closed as completed by joshuef** 2017-12-21 15:31 UTC
