### ISSUE TITLE
Have to restart Peruse to connect to the network

### ISSUE THREAD

**Issue by JPL1** [joshuef/peruse#53] opened 2018-02-03 10:02 UTC
It is often necessary to restart Peruse to connect to the network. I think this is because it's authenticating in the background now and sometimes that can take a bit of time. On loading a page the user is greeted with a "resource unavailable" type error (from memory - can't reproduce at the moment, typical ;) ), after which the only solution seems to be a reboot. Perhaps this message could be changed to add "please wait a moment or reboot the browser"?

Peruse version 0.4.1

**Comment by joshuef** [comment] 2018-02-06 08:40
Thank @JPL1 ! Closing as duplicate of #11

**Closed as completed by joshuef** 2018-02-06 08:40 UTC

**Comment by joshuef** [comment] 2018-02-06 08:42
FYI, the error itself is coming from the network, so I'd not opt to switch that per se. 

But we will be working in the reconnect functionality into an upcoming milestone, so this should ideally provide some of the missing UX feedback we need here 👍
